"""Build a dependency-free, accessible static portfolio from reviewed source copy."""
from pathlib import Path
from html import escape
import json
import shutil

ROOT = Path(__file__).parent
DIST = ROOT / 'dist'
ORIGIN = 'https://omarnabail.github.io'
EMAIL = 'omargamal039@gmail.com'
GH = 'https://github.com/OmarNabail'
LI = 'https://www.linkedin.com/in/omar-nabail/'
DEMO = 'https://huggingface.co/spaces/omargam220/PlotCraft'
REPO = GH + '/PlotCraft-Deployment'
GMAIL_COMPOSE = f'https://mail.google.com/mail/?view=cm&fs=1&to={EMAIL}'

def tags(items):
    return '<div class="tags">' + ''.join(f'<span class="tag">{escape(x)}</span>' for x in items) + '</div>'

def page(title, description, body, filename='index.html'):
    canonical = ORIGIN + ('/' if filename == 'index.html' else '/' + filename)
    schema = {'@context':'https://schema.org','@type':'Person','name':'Omar Nabail','url':ORIGIN,'sameAs':[GH,LI],'knowsAbout':['Machine learning','Python','Model evaluation','Software engineering'],'homeLocation':{'@type':'Country','name':'Germany'}}
    doc = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(title)}</title><meta name="description" content="{escape(description, quote=True)}"><meta name="theme-color" content="#5835c7">
<link rel="canonical" href="{canonical}"><meta property="og:type" content="website"><meta property="og:title" content="{escape(title, quote=True)}"><meta property="og:description" content="{escape(description, quote=True)}"><meta property="og:url" content="{canonical}"><meta name="twitter:card" content="summary">
<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='7' fill='%235835c7'/%3E%3Ctext x='20' y='27' text-anchor='middle' font-family='Arial' font-weight='bold' font-size='19' fill='white'%3EON%3C/text%3E%3C/svg%3E">
<link rel="stylesheet" href="styles.css"><script type="application/ld+json">{json.dumps(schema)}</script></head>
<body><a class="skip" href="#main">Skip to content</a><header class="topbar"><nav class="wrap nav" aria-label="Main navigation"><a class="brand" href="index.html"><span class="monogram" aria-hidden="true">ON</span>Omar Nabail</a><div class="navlinks"><a class="desktop-link" href="index.html#work">Selected work</a><a class="desktop-link" href="index.html#experience">Experience</a><a href="index.html#contact">Contact</a><a class="nav-cv" href="Omar-Nabail-CV.pdf">View CV</a></div></nav></header>
<main id="main">{body}</main>
<footer class="wrap footer"><span>© 2026 Omar Nabail · Germany</span><div class="footer-links"><a href="{GH}">GitHub</a><a href="{LI}">LinkedIn</a><a href="privacy.html">Privacy</a></div></footer></body></html>'''
    (DIST / filename).write_text(doc, encoding='utf-8')

hero_visual = '''<div class="hero-visual" aria-label="Illustration of the PlotCraft text-to-figure workflow"><div class="window-bar"><span>plotcraft / text to figure</span><span class="dots" aria-hidden="true"><i></i><i></i><i></i></span></div><div class="prompt"><small>01 / NATURAL LANGUAGE</small>“Create a bar chart with values 2, 5, and 3.”</div><div class="connector" aria-hidden="true"></div><div class="pipeline-core"><b>PlotCraft</b><span>Qwen2.5-3B · LoRA · SFT + GRPO</span></div><div class="connector" aria-hidden="true"></div><div class="output-box"><div class="output-code">import matplotlib<br>…<br>plt.bar(labels,<br>&nbsp;[2, 5, 3])<br>plt.show()</div><div class="chart"><svg viewBox="0 0 160 108" role="img" aria-label="Illustrative bar chart: A equals 2, B equals 5, C equals 3"><path d="M15 10V85H150" fill="none" stroke="#c2bbd2"/><path d="M15 55H150M15 25H150" stroke="#f0edf6"/><rect x="32" y="57" width="25" height="28" rx="2" fill="#b7a4eb"/><rect x="73" y="15" width="25" height="70" rx="2" fill="#6640cf"/><rect x="114" y="43" width="25" height="42" rx="2" fill="#9274df"/><g font-size="11" font-family="Arial" fill="#625773"><text x="40" y="102">A</text><text x="81" y="102">B</text><text x="122" y="102">C</text></g></svg></div></div><p class="visual-caption">Illustrative workflow · executable code + browser preview</p></div>'''

body = f'''<section class="hero wrap"><div class="hero-grid"><div><div class="eyebrow">AI &amp; software engineering</div><h1>AI systems.<br><span>Built to work.</span></h1><p class="hero-copy">I'm Omar Nabail. I build and evaluate AI systems—from model training and data pipelines to tested APIs and deployed applications.</p><div class="actions"><a class="button" href="#work">Explore my work</a><a class="button secondary" href="Omar-Nabail-CV.pdf">View CV</a></div><div class="location"><span>Based in Germany</span><span>M.Sc. AI &amp; Robotics · UTN</span></div></div>{hero_visual}</div><div class="proof-strip"><div><b>From research to deployment</b><span>Fine-tuning, evaluation, APIs &amp; CI/CD</span></div><div><b>Research &amp; industry collaboration</b><span>NLLG Lab · UTN / Revel8</span></div><div><b>Code you can explore</b><span>Public PlotCraft demo &amp; source</span></div></div></section>
<section class="section wrap" id="work"><div class="section-head"><div><div class="eyebrow">01 / Selected work</div><h2>Engineering, with evidence.</h2></div><p>A closer look at what I built, the decisions behind it, and how I evaluated the results.</p></div>
<article class="featured"><div class="feature-content"><span class="project-kicker">Generative AI · Text-to-visualization</span><h3>PlotCraft</h3><p>Scientific figures from natural language. I built the pipeline from dataset preparation and model fine-tuning to a public application with executable Matplotlib output.</p>{tags(['Python','PyTorch','Qwen2.5','FastAPI','Docker'])}<div class="actions"><a class="button" href="plotcraft.html">Read case study</a><a class="button secondary" href="{DEMO}">Try live demo</a></div></div><div class="feature-panel"><span class="project-kicker">From training data to a working product</span><div class="metrics"><div class="metric"><strong>97.0%</strong><span>Internal code-execution rate</span></div><div class="metric"><strong>53,846</strong><span>Filtered PYVEC examples</span></div></div><div class="stages" aria-label="Training sequence"><span>Dataset</span><i aria-hidden="true"></i><span>LoRA SFT</span><i aria-hidden="true"></i><span>GRPO</span></div><div class="text-links"><a href="{REPO}">Explore the source code</a></div></div></article>
<div class="project-grid"><article class="project-card"><div class="card-visual"><div class="mini-flow"><span>MIME</span><i></i><span>Parse</span><i></i><span>Classify</span></div><div class="mini-caption">Parser-first email analysis</div></div><div class="card-body"><span class="project-kicker">Industry collaboration</span><h3>Phishing analysis, from the input up.</h3><p>A MIME-aware preprocessing and classification pipeline combining local/cloud inference with fine-tuned language models.</p><div class="text-links"><a href="phishing.html">Explore the approach</a></div></div></article>
<article class="project-card"><div class="card-visual"><div class="auc"><div><strong>81.38%</strong><span>AUC</span></div><div><strong>72.29%</strong><span>Partial AUC</span></div></div><div class="mini-caption">Reported thesis evaluation</div></div><div class="card-body"><span class="project-kicker">Acoustic anomaly detection</span><h3>Listening for valve anomalies.</h3><p>Signal processing and learned audio representations for condition monitoring under domain shift.</p><div class="text-links"><a href="valve-monitoring.html">Read case study</a></div></div></article>
<article class="project-card"><div class="card-visual"><div class="mini-flow"><span>Hosts</span><i></i><span>Kafka</span><i></i><span>DuckDB</span></div><div class="mini-caption">Batch · compress · encrypt</div></div><div class="card-body"><span class="project-kicker">Distributed systems</span><h3>Making cluster behavior observable.</h3><p>Decentralized monitoring with streaming analytics, LZ4 compression, and separated encrypted data streams.</p><div class="text-links"><a href="cluster-monitoring.html">Explore the system</a></div></div></article></div>
<article class="research-banner"><div><span class="project-kicker">Agentic scientific figure generation</span><h3>One figure. Multiple representations.</h3></div><p>Designed and implemented a multi-stage workflow that interpreted natural-language requests, routed them to Python/Matplotlib, TikZ, or direct-image generation, selected among candidates, and evaluated results with execution checks, visual similarity, VLM judges, and human evaluation.</p></article>
<details class="more-projects"><summary>More work in retrieval, computer vision &amp; software</summary>
<article class="compact-project"><h4>Local RAG with Hybrid Retrieval &amp; Reranking</h4><div class="compact-content"><p class="project-tech">Ollama · LlamaIndex · ChromaDB · Sentence Transformers</p><ul><li>Built a local RAG application over product documentation and historical support tickets, covering document processing, indexing, retrieval, answer generation, and evaluation with Ragas.</li><li>Benchmarked BM25, dense-embedding, hybrid, and cross-encoder reranking retrieval on a hand-labelled query set using Recall@k and MRR; quantified trade-offs between retrieval accuracy, latency, and computational cost.</li><li>Developed a Streamlit dashboard for comparing retrieval configurations side by side.</li></ul></div></article>
<article class="compact-project"><h4>CAPTCHA Recognition</h4><p>CNN–Transformer architecture with deformable convolutions and triplet attention. Placed <strong>third among eight teams</strong> in the UTN 2025 Computer Vision Challenge. Python · PyTorch · OpenCV.</p></article>
<article class="compact-project"><h4>Multilingual Hate-Speech Evaluation</h4><p>Structured pipelines comparing GPT-4, Claude, and Qwen across languages, investigating differences in moderation fairness and consistency.</p></article>
<article class="compact-project"><h4>German Trash Classification</h4><p>Zero-shot waste-image classification with CLIP and a multilingual interface. The project reported 95.4% Top-5 accuracy on its real-world evaluation data; this is not a Top-1 result.</p></article>
<article class="compact-project"><h4>Airline Reservation System</h4><div class="compact-content"><p class="project-tech">JavaScript · Node.js · React · MongoDB</p><ul><li>Developed a full-stack flight-search and reservation application with a REST API using Node.js and Express, a MongoDB backend, and a React/Material UI frontend.</li><li>Implemented registration, login with encrypted password storage, flight booking, and automated email notifications via Nodemailer.</li></ul></div></article>
<article class="compact-project"><h4>Coast Guard AI Rescue Simulation</h4><div class="compact-content"><p class="project-tech">Java · Search Algorithms · Java Swing</p><ul><li>Built an autonomous agent navigating a dynamic sea grid with sinking ships, passenger rescue, black-box recovery, and time-dependent consequences.</li><li>Implemented eight search strategies, including BFS, DFS, iterative deepening, uniform-cost, greedy, and A*, with custom heuristics and a Swing interface for visualizing missions.</li></ul></div></article>
<article class="compact-project"><h4>Dance Floor: Interactive 3D Application</h4><div class="compact-content"><p class="project-tech">C++ · OpenGL · 3D Graphics</p><ul><li>Built an interactive real-time 3D environment with a controllable character, WASD movement, multiple dance animations, side, front, and free camera modes, custom mesh loading, and textured-model rendering.</li></ul></div></article>
<article class="compact-project"><h4>ShootAliens: 2D Shooter Game</h4><div class="compact-content"><p class="project-tech">C++ · OpenGL · GLUT</p><ul><li>Developed a complete two-level shooter with mouse-directed shooting, randomized enemy spawning, collision detection, a power-up mechanic, and timer-driven animation, progression, and win/lose states.</li></ul></div></article>
<article class="compact-project"><h4>Autonomous Car</h4><div class="compact-content"><p class="project-tech">C/C++ · Arduino · Processing · Fritzing</p><ul><li>Designed and built a physical autonomous vehicle; programmed motor-control and sensor-integration logic in C/C++ for an Arduino microcontroller and designed the circuit in Fritzing.</li><li>Built a Processing-based serial interface for real-time monitoring and documented the system architecture, components, and behaviour.</li></ul></div></article>
</details></section>
<section class="section tinted" id="experience"><div class="wrap experience-layout"><div><div class="eyebrow">02 / Experience &amp; education</div><h2 class="intro-heading">Research depth.<br>Engineering practice.</h2><p class="intro-text">My work connects machine learning experiments with the software needed to process data, evaluate failures, and make models usable.</p><div class="text-links"><a href="Omar-Nabail-CV.pdf">View full CV</a></div></div><div class="timeline">
<article class="timeline-item"><div class="timeline-meta">JUL 2026 – PRESENT</div><h3>Student Research Assistant</h3><div class="org">NLLG Lab · UTN</div><p>Contribute to research on generative multimodal models, covering evaluation methodology, failure-mode analysis, and result reporting across NLP and vision-language projects.</p></article>
<article class="timeline-item"><div class="timeline-meta">MAR 2025 – FEB 2026</div><h3>ML for Cybersecurity</h3><div class="org">UTN / Revel8 · Industry collaboration</div><p>Built a Python data-processing and classification pipeline combining parser-first preprocessing, local/cloud inference, and fine-tuned models. Analyzed model failure cases.</p></article>
<article class="timeline-item"><div class="timeline-meta">SEP 2024 – PRESENT</div><h3>M.Sc. Artificial Intelligence &amp; Robotics</h3><div class="org">University of Technology Nuremberg (UTN)</div></article>
<article class="timeline-item"><div class="timeline-meta">SEP 2017 – SEP 2023</div><h3>B.Sc. Computer Science &amp; Engineering</h3><div class="org">German University in Cairo</div><p>Bachelor’s thesis: acoustic anomaly detection for valve condition monitoring.</p></article></div></div></section>
<section class="section wrap" id="skills"><div class="section-head"><div><div class="eyebrow">03 / Technical toolkit</div><h2>Skills grounded in projects.</h2></div></div><div class="skills-grid"><article class="skill-block"><h3>Machine learning &amp; evaluation</h3><p>Fine-tuning, retrieval comparisons, image analysis, and failure-driven model evaluation.</p>{tags(['Python','PyTorch','Hugging Face','LoRA / SFT / GRPO','OpenCV','NumPy'])}</article><article class="skill-block"><h3>Software &amp; deployment</h3><p>APIs, containerized services, automated tests, and repeatable deployment workflows.</p>{tags(['FastAPI','REST APIs','Docker','pytest','GitHub Actions','Git / Linux'])}</article><article class="skill-block"><h3>Data &amp; systems</h3><p>Streaming data pipelines, analytical processing, compression, and GPU research workloads.</p>{tags(['SQL','Kafka','DuckDB','LZ4','Slurm','C / C++'])}</article></div><div class="language-row"><div><strong>English</strong> <span>Fluent · C1</span></div><div><strong>German</strong> <span>B1 completed · Preparing for B2 exam</span></div><div><strong>Arabic</strong> <span>Native</span></div></div></section>
<section class="contact" id="contact"><div class="wrap contact-inner"><div><div class="eyebrow">04 / Contact</div><h2>Let’s talk about the work.</h2><p>For AI, machine learning, and software engineering opportunities in Germany—or a closer look at a project.</p></div><div class="contact-action"><a class="button" href="{GMAIL_COMPOSE}" target="_blank" rel="noopener">Email Omar</a><div class="contact-links"><a href="{LI}">LinkedIn</a><a href="{GH}">GitHub</a><a href="Omar-Nabail-CV.pdf" download>Download CV</a></div><p style="font-size:.875rem;overflow-wrap:anywhere"><a href="mailto:{EMAIL}">{EMAIL}</a></p></div></div></section>'''
page('Omar Nabail | AI & Software Engineering in Germany','Omar Nabail builds and evaluates AI systems: model fine-tuning, retrieval, Python APIs, and deployed applications. Explore project evidence, research experience, and CV.',body)

cases = [
{'file':'plotcraft.html','title':'PlotCraft','label':'Generative AI · Model training · Deployment','lead':'From a natural-language instruction to executable scientific-figure code—and a public application to try it.','skills':['Python','PyTorch','Qwen2.5-3B','LoRA','SFT','GRPO','Matplotlib','FastAPI','Gradio','Docker','GitHub Actions'],'flow':['PYVEC','LoRA SFT','GRPO','API / Gradio','Browser preview'],'caption':'Training and serving workflow. Generated code is rendered in an isolated browser worker rather than executed on the application server.','sections':[
('The problem','<p>Generating a scientific figure involves more than producing an image: the underlying plotting code should execute and remain editable. PlotCraft turns text instructions into Python/Matplotlib code that users can review, render, and reuse.</p>'),
('What I built','<p>I developed the end-to-end system: prepared the filtered PYVEC dataset of 53,846 examples, built the training pipeline, fine-tuned Qwen2.5-3B with LoRA-based supervised fine-tuning followed by GRPO, and deployed the resulting application on Hugging Face ZeroGPU.</p><p>I also built a containerized FastAPI service, configuration and error handling, health checks, automated tests, and GitHub Actions workflows for validation, Docker builds, and deployment.</p>'),
('Engineering decisions','<ul><li><strong>Executable output:</strong> return Python/Matplotlib code so users can inspect and modify a figure.</li><li><strong>Training sequence:</strong> follow supervised fine-tuning with GRPO reinforcement learning.</li><li><strong>Browser-based rendering:</strong> execute the preview in an isolated browser worker with execution limits, keeping generated code off the application server.</li><li><strong>Reproducible delivery:</strong> package the API with Docker and use automated tests and CI/CD to validate changes.</li></ul>'),
('Result & evaluation','<div class="case-result"><b>97.0% internal code-execution rate after GRPO</b><p>This measures whether code executed in the internal evaluation. It does not establish visual quality, scientific correctness, or performance on an independent benchmark.</p></div><p>The deployed application makes the system inspectable: enter a prompt, review generated code, render a preview, and copy the code.</p>')], 'evidence':'The public demo and deployment repository provide inspectable evidence of the application, API, tests, and delivery workflow.','links':[(DEMO,'Try live demo'),(REPO,'View source code')]},
{'file':'phishing.html','title':'MIME-aware phishing analysis','label':'UTN / Revel8 · Industry collaboration','lead':'A parser-first pipeline for turning complex email content into structured model inputs and fine-grained phishing classifications.','skills':['Python','MIME parsing','Prompt engineering','Zero-shot','Few-shot','Chain-of-thought','RoBERTa','EmoBERTa','Local / cloud inference'],'flow':['MIME email','Parse & normalize','Prompt / model inference','Category evaluation'],'caption':'Conceptual processing sequence based on the implemented pipeline.','sections':[
('The problem','<p>MIME-formatted emails contain structure and content that must be processed before useful classification. The project addressed both preprocessing and the evaluation of fine-grained social-engineering categories.</p>'),
('What I built','<p>In the UTN/Revel8 industry collaboration, I built a Python preprocessing and classification pipeline, extracted and normalized relevant email content, supported local and cloud-based LLM inference, applied prompt engineering with zero-shot, few-shot, and chain-of-thought approaches, and fine-tuned RoBERTa and EmoBERTa classifiers.</p>'),
('Technical approach','<p>The parser-first design separates email processing from model inference. I compared prompting strategies and classifier-based approaches while evaluating intent, tactics, tools, and psychological triggers. Failure analysis was used to examine where each approach struggled.</p>'),
('Result & evidence','<p>The resulting system combines structured preprocessing, multiple inference strategies, and fine-grained classification. The work included analyzing model failure cases and connecting data preparation and prompting choices with downstream prediction quality.</p>')], 'evidence':'Described in the CV as an industry collaboration, March 2025–February 2026.','links':[]},
{'file':'valve-monitoring.html','title':'Valve condition monitoring','label':'Bachelor’s thesis · Acoustic anomaly detection','lead':'Learning from sound to investigate valve anomalies when operating conditions and data distributions change.','skills':['Python','PyTorch','DFT','Spectrograms','MobileFaceNet','Sub-cluster AdaCos'],'flow':['Audio','DFT / spectrograms','Learned representation','Anomaly evaluation'],'caption':'Conceptual architecture of the acoustic anomaly-detection work.','sections':[
('The problem','<p>Condition monitoring systems need to recognize anomalous behavior even when the data differ from the conditions seen during development. My bachelor’s thesis investigated acoustic anomaly detection for valves under domain shift.</p>'),
('What I built','<p>I developed an audio-processing and anomaly-detection pipeline, transformed signals into frequency-domain and spectrogram representations, and used MobileFaceNet with sub-cluster AdaCos for learned representations. I investigated outlier exposure under domain shift.</p>'),
('Reported results','<div class="case-result"><b>81.38% AUC · 72.29% partial AUC</b><p>Reported thesis evaluation results under domain shift. These are evaluation metrics, not classification accuracy.</p></div><p>The dataset split, partial-AUC operating range, and baseline comparison are not documented on this page; the figures should be read within the thesis evaluation context.</p>')], 'evidence':'Bachelor’s thesis at the German University in Cairo. Results are documented in the CV.','links':[]},
{'file':'cluster-monitoring.html','title':'Cluster performance analysis','label':'Distributed systems · Data engineering','lead':'Decentralized monitoring pipelines for performance analytics across cluster hosts and clients.','skills':['Python','Kafka','DuckDB','LZ4','Batching','Encrypted streams'],'flow':['Hosts / clients','Batch & compress','Kafka','DuckDB analytics'],'caption':'Conceptual data path. Customer and operator information use distinct encrypted streams.','sections':[
('The problem','<p>Distributed performance analysis requires a data path from cluster hosts and clients to analytical processing, while supporting different information-access needs for customers and operators.</p>'),
('What I built','<p>I developed decentralized monitoring pipelines using Kafka for streaming performance data and DuckDB for analytical processing. The implementation uses batching and LZ4 compression, with customer and operator information separated into distinct encrypted streams.</p>'),
('Engineering decisions','<ul><li><strong>Batching and compression:</strong> structure data transfer around batched payloads and LZ4 compression.</li><li><strong>Streaming and analysis:</strong> use Kafka for the data flow and DuckDB for analytical processing.</li><li><strong>Information separation:</strong> maintain different encrypted streams for customer and operator access patterns.</li></ul>'),
('Result & evidence','<p>The result is an implemented monitoring architecture combining streaming, compression, encryption, and analytical processing.</p>')], 'evidence':'Project implementation and technology choices are documented in the CV.','links':[]}
]
for c in cases:
    flow = '<i aria-hidden="true"></i>'.join('<span>'+escape(x)+'</span>' for x in c['flow'])
    sections = ''.join(f'<section><h2>{h}</h2>{p}</section>' for h,p in c['sections'])
    links = ''.join(f'<a class="button" href="{u}">{t}</a>' for u,t in c['links'])
    content = f'''<div class="wrap"><header class="case-hero"><a class="back-link" href="index.html#work">Back to selected work</a><p class="eyebrow">{c['label']}</p><h1>{c['title']}</h1><p class="case-lead">{c['lead']}</p></header><div class="case-layout"><article class="case-body"><figure class="architecture"><div class="stages">{flow}</div><figcaption>{c['caption']}</figcaption></figure>{sections}<div class="actions"><a class="button secondary" href="index.html#work">More selected work</a></div></article><aside class="case-aside"><h2>Technical toolkit</h2>{tags(c['skills'])}<h2>Evidence</h2><p>{c['evidence']}</p>{links}</aside></div></div>'''
    page(c['title']+' | Omar Nabail',c['lead'],content,c['file'])

page('Privacy | Omar Nabail','Privacy information for Omar Nabail’s portfolio.',f'''<div class="wrap"><article class="privacy"><a class="back-link" href="index.html">Back to portfolio</a><h1>Privacy</h1><p>This portfolio presents the work of Omar Nabail. For questions about the content, contact <a href="mailto:{EMAIL}">{EMAIL}</a>.</p><h2>How this website works</h2><p>The portfolio uses static pages. Its application code does not include visitor analytics, advertising trackers, a contact form, or browser-storage features.</p><h2>Hosting</h2><p>This website is hosted with GitHub Pages. GitHub may process technical request information, including visitor IP addresses, for security purposes. See <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub’s privacy statement</a> for details.</p><h2>External links and email</h2><p>GitHub, LinkedIn, and Hugging Face links take you to external services governed by their own privacy policies. Selecting an email link opens your email application; this website does not submit a message on your behalf.</p><h2>CV</h2><p>The downloadable CV contains professional background and contact information supplied by Omar Nabail.</p></article></div>''','privacy.html')

# Publish the user's current CV exactly as supplied.
source = Path(r'D:\summer26\job_application\master_cv.pdf')
shutil.copyfile(source, DIST/'Omar-Nabail-CV.pdf')

routes = ['index.html'] + [c['file'] for c in cases] + ['privacy.html']
(DIST/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+ORIGIN+('/' if p=='index.html' else '/'+p)+'</loc></url>' for p in routes)+'</urlset>',encoding='utf-8')
(DIST/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+ORIGIN+'/sitemap.xml\n',encoding='utf-8')
(DIST/'.nojekyll').write_text('',encoding='utf-8')
print(f'Generated {len(routes)} pages, sitemap, robots.txt, and updated CV copy.')
